/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.co.sistematransporte.vistas;

import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Leonardo Forero
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    Tarifas tar;
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnConsultas = new javax.swing.JButton();
        btnTarifas = new javax.swing.JButton();
        btnRutas = new javax.swing.JButton();
        btnVehiculos = new javax.swing.JButton();
        btnMedioTransporte = new javax.swing.JButton();
        btnFranjaHoraria = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        escritorio = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLayeredPane1.setMinimumSize(new java.awt.Dimension(200, 600));

        btnConsultas.setText("Consultas");
        jLayeredPane1.add(btnConsultas);
        btnConsultas.setBounds(10, 470, 170, 70);

        btnTarifas.setText("Tarifas");
        btnTarifas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarifasActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnTarifas);
        btnTarifas.setBounds(10, 70, 170, 70);

        btnRutas.setText("Rutas");
        jLayeredPane1.add(btnRutas);
        btnRutas.setBounds(10, 150, 170, 70);

        btnVehiculos.setText("Vehiculos");
        jLayeredPane1.add(btnVehiculos);
        btnVehiculos.setBounds(10, 230, 170, 70);

        btnMedioTransporte.setText("Medios Transporte");
        jLayeredPane1.add(btnMedioTransporte);
        btnMedioTransporte.setBounds(10, 310, 170, 70);

        btnFranjaHoraria.setText("Franja Horaria");
        jLayeredPane1.add(btnFranjaHoraria);
        btnFranjaHoraria.setBounds(10, 390, 170, 70);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 0, 200, 600);

        jLayeredPane2.setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jLayeredPane2.add(escritorio);
        escritorio.setBounds(0, 0, 580, 600);

        getContentPane().add(jLayeredPane2);
        jLayeredPane2.setBounds(200, 0, 600, 600);

        setSize(new java.awt.Dimension(800, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTarifasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarifasActionPerformed
        // TODO add your handling code here    
        try {
            if(estacerrado(tar)) {
                tar = new Tarifas();
                escritorio.add(tar);
                tar.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null,"La ventana de tarifas ya se encuentra abierta!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: "+e.getMessage());
        }
            
        
    }//GEN-LAST:event_btnTarifasActionPerformed
    public boolean estacerrado(Object obj){
    JInternalFrame[] activos=escritorio.getAllFrames();
    boolean cerrado=true;
    int i=0;
    while (i<activos.length && cerrado){
    if(activos[i]==obj){
    cerrado=false;
    }
    i++;
    }
    return cerrado;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnFranjaHoraria;
    private javax.swing.JButton btnMedioTransporte;
    private javax.swing.JButton btnRutas;
    private javax.swing.JButton btnTarifas;
    private javax.swing.JButton btnVehiculos;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    // End of variables declaration//GEN-END:variables
}
