/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.co.sistematransporte.vistas;

import com.co.sistematransporte.clases.MedioTransporte;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Leonardo Forero
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    Tarifas tar;
    Rutas rutas;
    Vehiculos veh;
    Paraderos par;
    Estacion est;
    FranjaHoraria franja;
    MediosTransporte medioTr;
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnConsultas = new javax.swing.JButton();
        btnTarifas = new javax.swing.JButton();
        btnRutas = new javax.swing.JButton();
        btnVehiculos = new javax.swing.JButton();
        btnMedioTransporte = new javax.swing.JButton();
        btnFranjaHoraria = new javax.swing.JButton();
        btnParaderos = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        escritorio = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLayeredPane1.setToolTipText("");
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(200, 600));

        btnConsultas.setText("Consultas");
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnConsultas);
        btnConsultas.setBounds(10, 410, 170, 70);

        btnTarifas.setText("Tarifas");
        btnTarifas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarifasActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnTarifas);
        btnTarifas.setBounds(10, 10, 170, 70);

        btnRutas.setText("Rutas");
        btnRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutasActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnRutas);
        btnRutas.setBounds(10, 90, 170, 70);

        btnVehiculos.setText("Vehiculos");
        btnVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculosActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnVehiculos);
        btnVehiculos.setBounds(10, 170, 170, 70);

        btnMedioTransporte.setText("Medios Transporte");
        btnMedioTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedioTransporteActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnMedioTransporte);
        btnMedioTransporte.setBounds(10, 250, 170, 70);

        btnFranjaHoraria.setText("Franja Horaria");
        btnFranjaHoraria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFranjaHorariaActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnFranjaHoraria);
        btnFranjaHoraria.setBounds(10, 330, 170, 70);

        btnParaderos.setText("Paraderos");
        btnParaderos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParaderosActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnParaderos);
        btnParaderos.setBounds(10, 490, 170, 70);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 0, 200, 600);

        jLayeredPane2.setPreferredSize(new java.awt.Dimension(600, 600));

        escritorio.setMinimumSize(new java.awt.Dimension(600, 600));
        escritorio.setPreferredSize(new java.awt.Dimension(600, 600));
        escritorio.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        jLayeredPane2.add(escritorio);
        escritorio.setBounds(0, 0, 600, 680);

        getContentPane().add(jLayeredPane2);
        jLayeredPane2.setBounds(200, 0, 600, 3000);

        setSize(new java.awt.Dimension(816, 638));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTarifasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarifasActionPerformed
        // TODO add your handling code here    
        try {
            if(estacerrado(tar)) {
                tar = new Tarifas();
                escritorio.add(tar);
                tar.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null,"La ventana de tarifas ya se encuentra abierta!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: "+e.getMessage());
        }
    }//GEN-LAST:event_btnTarifasActionPerformed

    private void btnRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutasActionPerformed
        // TODO add your handling code here:
        try {
            if(estacerrado(rutas)) {
                rutas = new Rutas();
                escritorio.add(rutas);
                rutas.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null,"La ventana de rutas ya se encuentra abierta!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: "+e.getMessage());
        }
    }//GEN-LAST:event_btnRutasActionPerformed

    private void btnVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculosActionPerformed
        // TODO add your handling code here:
        try {
            if(estacerrado(veh)) {
                veh = new Vehiculos();
                escritorio.add(veh);
                veh.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null,"La ventana de Vehiculos ya se encuentra abierta!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: "+e.getMessage());
        }
    }//GEN-LAST:event_btnVehiculosActionPerformed

    private void btnMedioTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedioTransporteActionPerformed
        // TODO add your handling code here:
        try {
            if(estacerrado(medioTr)) {
                medioTr = new MediosTransporte();
                escritorio.add(medioTr);
                medioTr.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null,"La ventana de Medio de Transporte ya se encuentra abierta!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: "+e.getMessage());
        }
    }//GEN-LAST:event_btnMedioTransporteActionPerformed

    private void btnFranjaHorariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFranjaHorariaActionPerformed
        // TODO add your handling code here:
        try {
            if(estacerrado(franja)) {
                franja = new FranjaHoraria();
                escritorio.add(franja);
                franja.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null,"La ventana Franja Horaria ya se encuentra abierta!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: "+e.getMessage());
        }
    }//GEN-LAST:event_btnFranjaHorariaActionPerformed

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnConsultasActionPerformed

    private void btnParaderosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParaderosActionPerformed
        // TODO add your handling code here:
        try {
            if(estacerrado(par)) {
                par = new Paraderos();
                escritorio.add(par);
                par.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null,"La ventana Franja Horaria ya se encuentra abierta!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: "+e.getMessage());
        }
    }//GEN-LAST:event_btnParaderosActionPerformed
   
    public boolean estacerrado(Object obj){
        JInternalFrame[] activos=escritorio.getAllFrames();
        boolean cerrado=true;
        int i=0;
        while (i<activos.length && cerrado){
            if(activos[i]==obj){
                cerrado=false;
            }
            i++;
        }
        return cerrado;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnFranjaHoraria;
    private javax.swing.JButton btnMedioTransporte;
    private javax.swing.JButton btnParaderos;
    private javax.swing.JButton btnRutas;
    private javax.swing.JButton btnTarifas;
    private javax.swing.JButton btnVehiculos;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    // End of variables declaration//GEN-END:variables
}
